service: report-processor-api-v7

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 28
  environment:
    STAGE: ${self:provider.stage}
    UPLOADS_BUCKET: !Ref UploadsBucket
    RESULTS_BUCKET: !Ref ResultsBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - !Sub "arn:aws:s3:::${UploadsBucket}/*"
            - !Sub "arn:aws:s3:::${ResultsBucket}/*"

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node20

# No necesitamos custom buckets - AWS generará nombres únicos automáticamente

functions:
  createReport:
    handler: src/interfaces/lambda/createReportHandler.handler
    timeout: 29
    events:
      - http:
          path: reports
          method: post
          cors: true

  processCSV:
    handler: src/interfaces/lambda/processCsvHandler.handler
    timeout: 300
    events:
      - s3:
          bucket: !Ref UploadsBucket
          event: s3:ObjectCreated:*
          existing: true

  getReport:
    handler: src/interfaces/lambda/getReportHandler.handler
    timeout: 29
    events:
      - http:
          path: reports/{reportId}
          method: get
          cors: true

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000

    ResultsBucket:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000



  Outputs:
    UploadsBucketName:
      Value: !Ref UploadsBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-uploads-bucket
    
    ResultsBucketName:
      Value: !Ref ResultsBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-results-bucket
